env:
  - GO111MODULE=on
before:
  hooks:
  - go mod download
builds:
  -
    id: knoxite
    binary: knoxite
    dir: cmd/knoxite
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - freebsd
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7

archives:
  - id: default
    builds:
      - knoxite
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      darwin: Darwin
      386: i386
      amd64: x86_64

nfpms:
  -
    builds:
    - knoxite

    vendor: knoxite
    homepage: "https://knoxite.com/"
    maintainer: "Christian Muehlhaeuser <muesli@gmail.com>"
    description: "An open-source data storage & backup system"
    license: AGPL
    formats:
      - deb
      - rpm
    bindir: /usr/bin

brews:
  - ids:
    - default
    goarm: 6
    tap:
      owner: knoxite
      name: homebrew-tap
    commit_author:
      name: "Christian Muehlhaeuser"
      email: "muesli@gmail.com"
    homepage: "https://knoxite.com/"
    description: "An open-source data storage & backup system"
    # skip_upload: true

signs:
  - artifacts: checksum

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
